tests:
  podStatus:
    timeouts:
      counts: 10
      seconds: 3
  springboot:
    since: "10h"
    timeouts:
      counts: 15
      seconds: 10

app:
  name: "mail"
  artifact: "mail-server"

conf:
  url: "http://app.XXX.local:5000/conf"
  profiles: "dev, sysdev"

auth:
  realm: ""

k8s:
  inCluster: false
  cluster: ""
  namespace: ""
